Create api demo for rapid api #5
hatchways/team-angelfish pull request #25
Opened 2021-03-09 15:13 UTC by Tojonirina4

I created 3 examples
1. Simple get
2. get with required params
3. get with required params and optional query

2021-03-09 17:47 UTC, gbudjeakp approved these changes

2021-03-09 18:13 UTC, johnsciutto requested changes

2021-03-09 18:13 UTC, johnsciutto commented on server/routes/flight.js
> +const rapidApiHost = "skyscanner-skyscanner-flight-search-v1.p.rapidapi.com";
I suggest putting this information in the `.env` file.

2021-03-09 18:36 UTC, sina-jamshidi commented on server/app.js
> +const port = process.env.port || 3001;
shouldn't be necessary

2021-03-09 18:57 UTC, sina-jamshidi commented on server/app.js
> +
not necessary

2021-03-09 18:57 UTC, sina-jamshidi approved these changes
This should be fine once you remove the port and figure out the `npm run dev`

2021-03-10 00:26 UTC, johnsciutto approved these changes

2021-03-10 06:13 UTC, merged